/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Announcement = IDL.Record({
  'id' : IDL.Nat,
  'contentHindi' : IDL.Text,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'titleHindi' : IDL.Text,
  'date' : Time,
  'isActive' : IDL.Bool,
});
export const ChangeLog = IDL.Record({
  'id' : IDL.Nat,
  'entity' : IDL.Text,
  'userName' : IDL.Text,
  'action' : IDL.Text,
  'timestamp' : Time,
  'details' : IDL.Text,
  'entityName' : IDL.Text,
});
export const Cow = IDL.Record({
  'id' : IDL.Nat,
  'age' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'healthStatus' : IDL.Text,
  'addedDate' : Time,
  'breed' : IDL.Text,
  'tagNumber' : IDL.Text,
  'qrCode' : IDL.Text,
});
export const Donation = IDL.Record({
  'id' : IDL.Nat,
  'date' : Time,
  'donorName' : IDL.Text,
  'message' : IDL.Text,
  'amount' : IDL.Float64,
  'purpose' : IDL.Text,
});
export const MilkRecord = IDL.Record({
  'id' : IDL.Nat,
  'morning' : IDL.Float64,
  'evening' : IDL.Float64,
  'changedBy' : IDL.Text,
  'cowName' : IDL.Text,
  'date' : IDL.Text,
  'cowId' : IDL.Nat,
  'addedDate' : Time,
});
export const User = IDL.Record({
  'id' : IDL.Nat,
  'pin' : IDL.Text,
  'name' : IDL.Text,
  'role' : IDL.Text,
});
export const Calf = IDL.Record({
  'id' : IDL.Nat,
  'birthYear' : IDL.Nat,
  'cowId' : IDL.Nat,
  'gender' : IDL.Text,
  'notes' : IDL.Text,
  'birthMonth' : IDL.Nat,
  'addedDate' : Time,
  'tagNumber' : IDL.Text,
});
export const FeedHistory = IDL.Record({
  'id' : IDL.Nat,
  'action' : IDL.Text,
  'date' : Time,
  'feedType' : IDL.Text,
  'recordedBy' : IDL.Text,
  'notes' : IDL.Text,
  'quantity' : IDL.Float64,
});
export const FeedStock = IDL.Record({
  'id' : IDL.Nat,
  'lastUpdated' : Time,
  'feedType' : IDL.Text,
  'updatedBy' : IDL.Text,
  'totalStock' : IDL.Float64,
  'dailyPerCow' : IDL.Float64,
});
export const HealthRecord = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'date' : Time,
  'cowId' : IDL.Nat,
  'vetName' : IDL.Text,
  'notes' : IDL.Text,
});
export const GaushaalaProfile = IDL.Record({
  'descriptionHindi' : IDL.Text,
  'nameHindi' : IDL.Text,
  'logoBase64' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'addAnnouncement' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addCalf' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addChangeLog' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'addCow' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'addDonation' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addFeedStockQuantity' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'addHealthRecord' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addMilkRecord' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Float64, IDL.Float64, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'changeUserPin' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  'createUser' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'deleteCalf' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'deleteCow' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'deleteMilkRecord' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'deleteUser' : IDL.Func([IDL.Nat], [], []),
  'ensureDefaultAdmin' : IDL.Func([], [], []),
  'getActiveAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
  'getAllChangeLogs' : IDL.Func([], [IDL.Vec(ChangeLog)], ['query']),
  'getAllCows' : IDL.Func([], [IDL.Vec(Cow)], ['query']),
  'getAllDonations' : IDL.Func([], [IDL.Vec(Donation)], ['query']),
  'getAllMilkRecords' : IDL.Func([], [IDL.Vec(MilkRecord)], ['query']),
  'getAllUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
  'getAnnouncement' : IDL.Func([IDL.Nat], [Announcement], ['query']),
  'getCalvesByCow' : IDL.Func([IDL.Nat], [IDL.Vec(Calf)], ['query']),
  'getCow' : IDL.Func([IDL.Nat], [Cow], ['query']),
  'getCowByTag' : IDL.Func([IDL.Text], [IDL.Opt(Cow)], ['query']),
  'getDonation' : IDL.Func([IDL.Nat], [Donation], ['query']),
  'getFeedHistory' : IDL.Func([], [IDL.Vec(FeedHistory)], ['query']),
  'getFeedStocks' : IDL.Func([], [IDL.Vec(FeedStock)], ['query']),
  'getHealthRecord' : IDL.Func([IDL.Nat], [HealthRecord], ['query']),
  'getHealthRecordsByCow' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(HealthRecord)],
      ['query'],
    ),
  'getMilkRecordsByDate' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(MilkRecord)],
      ['query'],
    ),
  'getOnlineUsers' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
  'getProfile' : IDL.Func([], [GaushaalaProfile], ['query']),
  'getTodayMilkRecords' : IDL.Func([], [IDL.Vec(MilkRecord)], ['query']),
  'getUserByPin' : IDL.Func([IDL.Text], [IDL.Opt(User)], ['query']),
  'getUsersByPin' : IDL.Func([IDL.Text], [IDL.Vec(User)], ['query']),
  'recordFeedConsumption' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'sendHeartbeat' : IDL.Func([IDL.Nat], [], []),
  'updateCow' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
  'updateFeedStock' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Float64, IDL.Text],
      [],
      [],
    ),
  'updateProfile' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Announcement = IDL.Record({
    'id' : IDL.Nat,
    'contentHindi' : IDL.Text,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'titleHindi' : IDL.Text,
    'date' : Time,
    'isActive' : IDL.Bool,
  });
  const ChangeLog = IDL.Record({
    'id' : IDL.Nat,
    'entity' : IDL.Text,
    'userName' : IDL.Text,
    'action' : IDL.Text,
    'timestamp' : Time,
    'details' : IDL.Text,
    'entityName' : IDL.Text,
  });
  const Cow = IDL.Record({
    'id' : IDL.Nat,
    'age' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'healthStatus' : IDL.Text,
    'addedDate' : Time,
    'breed' : IDL.Text,
    'tagNumber' : IDL.Text,
    'qrCode' : IDL.Text,
  });
  const Donation = IDL.Record({
    'id' : IDL.Nat,
    'date' : Time,
    'donorName' : IDL.Text,
    'message' : IDL.Text,
    'amount' : IDL.Float64,
    'purpose' : IDL.Text,
  });
  const MilkRecord = IDL.Record({
    'id' : IDL.Nat,
    'morning' : IDL.Float64,
    'evening' : IDL.Float64,
    'changedBy' : IDL.Text,
    'cowName' : IDL.Text,
    'date' : IDL.Text,
    'cowId' : IDL.Nat,
    'addedDate' : Time,
  });
  const User = IDL.Record({
    'id' : IDL.Nat,
    'pin' : IDL.Text,
    'name' : IDL.Text,
    'role' : IDL.Text,
  });
  const Calf = IDL.Record({
    'id' : IDL.Nat,
    'birthYear' : IDL.Nat,
    'cowId' : IDL.Nat,
    'gender' : IDL.Text,
    'notes' : IDL.Text,
    'birthMonth' : IDL.Nat,
    'addedDate' : Time,
    'tagNumber' : IDL.Text,
  });
  const FeedHistory = IDL.Record({
    'id' : IDL.Nat,
    'action' : IDL.Text,
    'date' : Time,
    'feedType' : IDL.Text,
    'recordedBy' : IDL.Text,
    'notes' : IDL.Text,
    'quantity' : IDL.Float64,
  });
  const FeedStock = IDL.Record({
    'id' : IDL.Nat,
    'lastUpdated' : Time,
    'feedType' : IDL.Text,
    'updatedBy' : IDL.Text,
    'totalStock' : IDL.Float64,
    'dailyPerCow' : IDL.Float64,
  });
  const HealthRecord = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'date' : Time,
    'cowId' : IDL.Nat,
    'vetName' : IDL.Text,
    'notes' : IDL.Text,
  });
  const GaushaalaProfile = IDL.Record({
    'descriptionHindi' : IDL.Text,
    'nameHindi' : IDL.Text,
    'logoBase64' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'addAnnouncement' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addCalf' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addChangeLog' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'addCow' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'addDonation' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addFeedStockQuantity' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'addHealthRecord' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addMilkRecord' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Float64, IDL.Float64, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'changeUserPin' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
    'createUser' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
    'deleteCalf' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'deleteCow' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'deleteMilkRecord' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'deleteUser' : IDL.Func([IDL.Nat], [], []),
    'ensureDefaultAdmin' : IDL.Func([], [], []),
    'getActiveAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
    'getAllChangeLogs' : IDL.Func([], [IDL.Vec(ChangeLog)], ['query']),
    'getAllCows' : IDL.Func([], [IDL.Vec(Cow)], ['query']),
    'getAllDonations' : IDL.Func([], [IDL.Vec(Donation)], ['query']),
    'getAllMilkRecords' : IDL.Func([], [IDL.Vec(MilkRecord)], ['query']),
    'getAllUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
    'getAnnouncement' : IDL.Func([IDL.Nat], [Announcement], ['query']),
    'getCalvesByCow' : IDL.Func([IDL.Nat], [IDL.Vec(Calf)], ['query']),
    'getCow' : IDL.Func([IDL.Nat], [Cow], ['query']),
    'getCowByTag' : IDL.Func([IDL.Text], [IDL.Opt(Cow)], ['query']),
    'getDonation' : IDL.Func([IDL.Nat], [Donation], ['query']),
    'getFeedHistory' : IDL.Func([], [IDL.Vec(FeedHistory)], ['query']),
    'getFeedStocks' : IDL.Func([], [IDL.Vec(FeedStock)], ['query']),
    'getHealthRecord' : IDL.Func([IDL.Nat], [HealthRecord], ['query']),
    'getHealthRecordsByCow' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(HealthRecord)],
        ['query'],
      ),
    'getMilkRecordsByDate' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(MilkRecord)],
        ['query'],
      ),
    'getOnlineUsers' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
    'getProfile' : IDL.Func([], [GaushaalaProfile], ['query']),
    'getTodayMilkRecords' : IDL.Func([], [IDL.Vec(MilkRecord)], ['query']),
    'getUserByPin' : IDL.Func([IDL.Text], [IDL.Opt(User)], ['query']),
    'getUsersByPin' : IDL.Func([IDL.Text], [IDL.Vec(User)], ['query']),
    'recordFeedConsumption' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'sendHeartbeat' : IDL.Func([IDL.Nat], [], []),
    'updateCow' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
    'updateFeedStock' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Float64, IDL.Text],
        [],
        [],
      ),
    'updateProfile' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };