/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Announcement {
  'id' : bigint,
  'contentHindi' : string,
  'title' : string,
  'content' : string,
  'titleHindi' : string,
  'date' : Time,
  'isActive' : boolean,
}
export interface Calf {
  'id' : bigint,
  'birthYear' : bigint,
  'cowId' : bigint,
  'gender' : string,
  'notes' : string,
  'birthMonth' : bigint,
  'addedDate' : Time,
  'tagNumber' : string,
}
export interface ChangeLog {
  'id' : bigint,
  'entity' : string,
  'userName' : string,
  'action' : string,
  'timestamp' : Time,
  'details' : string,
  'entityName' : string,
}
export interface Cow {
  'id' : bigint,
  'age' : bigint,
  'name' : string,
  'description' : string,
  'healthStatus' : string,
  'addedDate' : Time,
  'breed' : string,
  'tagNumber' : string,
  'qrCode' : string,
}
export interface Donation {
  'id' : bigint,
  'date' : Time,
  'donorName' : string,
  'message' : string,
  'amount' : number,
  'purpose' : string,
}
export interface FeedHistory {
  'id' : bigint,
  'action' : string,
  'date' : Time,
  'feedType' : string,
  'recordedBy' : string,
  'notes' : string,
  'quantity' : number,
}
export interface FeedStock {
  'id' : bigint,
  'lastUpdated' : Time,
  'feedType' : string,
  'updatedBy' : string,
  'totalStock' : number,
  'dailyPerCow' : number,
}
export interface GaushaalaProfile {
  'descriptionHindi' : string,
  'nameHindi' : string,
  'logoBase64' : string,
  'name' : string,
  'description' : string,
  'address' : string,
  'phone' : string,
}
export interface HealthRecord {
  'id' : bigint,
  'status' : string,
  'date' : Time,
  'cowId' : bigint,
  'vetName' : string,
  'notes' : string,
}
export interface MilkRecord {
  'id' : bigint,
  'morning' : number,
  'evening' : number,
  'changedBy' : string,
  'cowName' : string,
  'date' : string,
  'cowId' : bigint,
  'addedDate' : Time,
}
export type Time = bigint;
export interface User {
  'id' : bigint,
  'pin' : string,
  'name' : string,
  'role' : string,
}
export interface _SERVICE {
  'addAnnouncement' : ActorMethod<
    [string, string, string, string, boolean, string],
    bigint
  >,
  'addCalf' : ActorMethod<
    [bigint, bigint, bigint, string, string, string, string],
    bigint
  >,
  'addChangeLog' : ActorMethod<
    [string, string, string, string, string],
    undefined
  >,
  'addCow' : ActorMethod<
    [string, string, bigint, string, string, string, string, string],
    bigint
  >,
  'addDonation' : ActorMethod<[string, number, string, string, string], bigint>,
  'addFeedStockQuantity' : ActorMethod<
    [string, number, string, string],
    undefined
  >,
  'addHealthRecord' : ActorMethod<
    [bigint, string, string, string, string],
    bigint
  >,
  'addMilkRecord' : ActorMethod<
    [bigint, string, string, number, number, string],
    bigint
  >,
  'changeUserPin' : ActorMethod<[bigint, string, string], undefined>,
  'createUser' : ActorMethod<[string, string, string], bigint>,
  'deleteCalf' : ActorMethod<[bigint, string], undefined>,
  'deleteCow' : ActorMethod<[bigint, string], undefined>,
  'deleteMilkRecord' : ActorMethod<[bigint, string], undefined>,
  'deleteUser' : ActorMethod<[bigint], undefined>,
  'ensureDefaultAdmin' : ActorMethod<[], undefined>,
  'getActiveAnnouncements' : ActorMethod<[], Array<Announcement>>,
  'getAllChangeLogs' : ActorMethod<[], Array<ChangeLog>>,
  'getAllCows' : ActorMethod<[], Array<Cow>>,
  'getAllDonations' : ActorMethod<[], Array<Donation>>,
  'getAllMilkRecords' : ActorMethod<[], Array<MilkRecord>>,
  'getAllUsers' : ActorMethod<[], Array<User>>,
  'getAnnouncement' : ActorMethod<[bigint], Announcement>,
  'getCalvesByCow' : ActorMethod<[bigint], Array<Calf>>,
  'getCow' : ActorMethod<[bigint], Cow>,
  'getCowByTag' : ActorMethod<[string], [] | [Cow]>,
  'getDonation' : ActorMethod<[bigint], Donation>,
  'getFeedHistory' : ActorMethod<[], Array<FeedHistory>>,
  'getFeedStocks' : ActorMethod<[], Array<FeedStock>>,
  'getHealthRecord' : ActorMethod<[bigint], HealthRecord>,
  'getHealthRecordsByCow' : ActorMethod<[bigint], Array<HealthRecord>>,
  'getMilkRecordsByDate' : ActorMethod<[string], Array<MilkRecord>>,
  'getOnlineUsers' : ActorMethod<[], Array<bigint>>,
  'getProfile' : ActorMethod<[], GaushaalaProfile>,
  'getTodayMilkRecords' : ActorMethod<[], Array<MilkRecord>>,
  'getUserByPin' : ActorMethod<[string], [] | [User]>,
  'getUsersByPin' : ActorMethod<[string], Array<User>>,
  'recordFeedConsumption' : ActorMethod<
    [string, number, string, string],
    undefined
  >,
  'sendHeartbeat' : ActorMethod<[bigint], undefined>,
  'updateCow' : ActorMethod<
    [bigint, string, string, bigint, string, string, string, string, string],
    undefined
  >,
  'updateFeedStock' : ActorMethod<[string, number, number, string], undefined>,
  'updateProfile' : ActorMethod<
    [string, string, string, string, string, string, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];