/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface MilkRecord {
    id: bigint;
    morning: number;
    evening: number;
    changedBy: string;
    cowName: string;
    date: string;
    cowId: bigint;
    addedDate: Time;
}
export interface Donation {
    id: bigint;
    date: Time;
    donorName: string;
    message: string;
    amount: number;
    purpose: string;
}
export type Time = bigint;
export interface User {
    id: bigint;
    pin: string;
    name: string;
    role: string;
}
export interface FeedHistory {
    id: bigint;
    action: string;
    date: Time;
    feedType: string;
    recordedBy: string;
    notes: string;
    quantity: number;
}
export interface Cow {
    id: bigint;
    age: bigint;
    name: string;
    description: string;
    healthStatus: string;
    addedDate: Time;
    breed: string;
    tagNumber: string;
    qrCode: string;
}
export interface Calf {
    id: bigint;
    birthYear: bigint;
    cowId: bigint;
    gender: string;
    notes: string;
    birthMonth: bigint;
    addedDate: Time;
    tagNumber: string;
}
export interface HealthRecord {
    id: bigint;
    status: string;
    date: Time;
    cowId: bigint;
    vetName: string;
    notes: string;
}
export interface FeedStock {
    id: bigint;
    lastUpdated: Time;
    feedType: string;
    updatedBy: string;
    totalStock: number;
    dailyPerCow: number;
}
export interface ChangeLog {
    id: bigint;
    entity: string;
    userName: string;
    action: string;
    timestamp: Time;
    details: string;
    entityName: string;
}
export interface GaushaalaProfile {
    descriptionHindi: string;
    nameHindi: string;
    logoBase64: string;
    name: string;
    description: string;
    address: string;
    phone: string;
}
export interface Announcement {
    id: bigint;
    contentHindi: string;
    title: string;
    content: string;
    titleHindi: string;
    date: Time;
    isActive: boolean;
}
export interface backendInterface {
    addAnnouncement(title: string, titleHindi: string, content: string, contentHindi: string, isActive: boolean, changedBy: string): Promise<bigint>;
    addCalf(cowId: bigint, birthMonth: bigint, birthYear: bigint, gender: string, tagNumber: string, notes: string, changedBy: string): Promise<bigint>;
    addChangeLog(userName: string, action: string, entity: string, entityName: string, details: string): Promise<void>;
    addCow(name: string, breed: string, age: bigint, healthStatus: string, description: string, tagNumber: string, qrCode: string, changedBy: string): Promise<bigint>;
    addDonation(donorName: string, amount: number, message: string, purpose: string, changedBy: string): Promise<bigint>;
    addFeedStockQuantity(feedType: string, quantity: number, notes: string, recordedBy: string): Promise<void>;
    addHealthRecord(cowId: bigint, notes: string, status: string, vetName: string, changedBy: string): Promise<bigint>;
    addMilkRecord(cowId: bigint, cowName: string, date: string, morning: number, evening: number, changedBy: string): Promise<bigint>;
    changeUserPin(id: bigint, newPin: string, changedBy: string): Promise<void>;
    createUser(name: string, role: string, pin: string): Promise<bigint>;
    deleteCalf(id: bigint, changedBy: string): Promise<void>;
    deleteCow(id: bigint, changedBy: string): Promise<void>;
    deleteMilkRecord(id: bigint, changedBy: string): Promise<void>;
    deleteUser(id: bigint): Promise<void>;
    ensureDefaultAdmin(): Promise<void>;
    getActiveAnnouncements(): Promise<Array<Announcement>>;
    getAllChangeLogs(): Promise<Array<ChangeLog>>;
    getAllCows(): Promise<Array<Cow>>;
    getAllDonations(): Promise<Array<Donation>>;
    getAllMilkRecords(): Promise<Array<MilkRecord>>;
    getAllUsers(): Promise<Array<User>>;
    getAnnouncement(id: bigint): Promise<Announcement>;
    getCalvesByCow(cowId: bigint): Promise<Array<Calf>>;
    getCow(id: bigint): Promise<Cow>;
    getCowByTag(tag: string): Promise<Cow | null>;
    getDonation(id: bigint): Promise<Donation>;
    getFeedHistory(): Promise<Array<FeedHistory>>;
    getFeedStocks(): Promise<Array<FeedStock>>;
    getHealthRecord(id: bigint): Promise<HealthRecord>;
    getHealthRecordsByCow(cowId: bigint): Promise<Array<HealthRecord>>;
    getMilkRecordsByDate(date: string): Promise<Array<MilkRecord>>;
    getOnlineUsers(): Promise<Array<bigint>>;
    getProfile(): Promise<GaushaalaProfile>;
    getTodayMilkRecords(): Promise<Array<MilkRecord>>;
    getUserByPin(pin: string): Promise<User | null>;
    getUsersByPin(pin: string): Promise<Array<User>>;
    recordFeedConsumption(feedType: string, quantity: number, notes: string, recordedBy: string): Promise<void>;
    sendHeartbeat(userId: bigint): Promise<void>;
    updateCow(id: bigint, name: string, breed: string, age: bigint, healthStatus: string, description: string, tagNumber: string, qrCode: string, changedBy: string): Promise<void>;
    updateFeedStock(feedType: string, totalStock: number, dailyPerCow: number, updatedBy: string): Promise<void>;
    updateProfile(name: string, nameHindi: string, description: string, descriptionHindi: string, phone: string, address: string, logoBase64: string, changedBy: string): Promise<void>;
}
import type { Cow as _Cow, User as _User } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addAnnouncement(arg0: string, arg1: string, arg2: string, arg3: string, arg4: boolean, arg5: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addAnnouncement(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAnnouncement(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async addCalf(arg0: bigint, arg1: bigint, arg2: bigint, arg3: string, arg4: string, arg5: string, arg6: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addCalf(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCalf(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async addChangeLog(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addChangeLog(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addChangeLog(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async addCow(arg0: string, arg1: string, arg2: bigint, arg3: string, arg4: string, arg5: string, arg6: string, arg7: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addCow(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCow(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async addDonation(arg0: string, arg1: number, arg2: string, arg3: string, arg4: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addDonation(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDonation(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async addFeedStockQuantity(arg0: string, arg1: number, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addFeedStockQuantity(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFeedStockQuantity(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async addHealthRecord(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addHealthRecord(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addHealthRecord(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async addMilkRecord(arg0: bigint, arg1: string, arg2: string, arg3: number, arg4: number, arg5: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addMilkRecord(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMilkRecord(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async changeUserPin(arg0: bigint, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.changeUserPin(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.changeUserPin(arg0, arg1, arg2);
            return result;
        }
    }
    async createUser(arg0: string, arg1: string, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createUser(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createUser(arg0, arg1, arg2);
            return result;
        }
    }
    async deleteCalf(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCalf(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCalf(arg0, arg1);
            return result;
        }
    }
    async deleteCow(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCow(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCow(arg0, arg1);
            return result;
        }
    }
    async deleteMilkRecord(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMilkRecord(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMilkRecord(arg0, arg1);
            return result;
        }
    }
    async deleteUser(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteUser(arg0);
            return result;
        }
    }
    async ensureDefaultAdmin(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.ensureDefaultAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.ensureDefaultAdmin();
            return result;
        }
    }
    async getActiveAnnouncements(): Promise<Array<Announcement>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveAnnouncements();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveAnnouncements();
            return result;
        }
    }
    async getAllChangeLogs(): Promise<Array<ChangeLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllChangeLogs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllChangeLogs();
            return result;
        }
    }
    async getAllCows(): Promise<Array<Cow>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCows();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCows();
            return result;
        }
    }
    async getAllDonations(): Promise<Array<Donation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDonations();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDonations();
            return result;
        }
    }
    async getAllMilkRecords(): Promise<Array<MilkRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMilkRecords();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMilkRecords();
            return result;
        }
    }
    async getAllUsers(): Promise<Array<User>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsers();
            return result;
        }
    }
    async getAnnouncement(arg0: bigint): Promise<Announcement> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnnouncement(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnnouncement(arg0);
            return result;
        }
    }
    async getCalvesByCow(arg0: bigint): Promise<Array<Calf>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCalvesByCow(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCalvesByCow(arg0);
            return result;
        }
    }
    async getCow(arg0: bigint): Promise<Cow> {
        if (this.processError) {
            try {
                const result = await this.actor.getCow(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCow(arg0);
            return result;
        }
    }
    async getCowByTag(arg0: string): Promise<Cow | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCowByTag(arg0);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCowByTag(arg0);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDonation(arg0: bigint): Promise<Donation> {
        if (this.processError) {
            try {
                const result = await this.actor.getDonation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDonation(arg0);
            return result;
        }
    }
    async getFeedHistory(): Promise<Array<FeedHistory>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeedHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeedHistory();
            return result;
        }
    }
    async getFeedStocks(): Promise<Array<FeedStock>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeedStocks();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeedStocks();
            return result;
        }
    }
    async getHealthRecord(arg0: bigint): Promise<HealthRecord> {
        if (this.processError) {
            try {
                const result = await this.actor.getHealthRecord(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHealthRecord(arg0);
            return result;
        }
    }
    async getHealthRecordsByCow(arg0: bigint): Promise<Array<HealthRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHealthRecordsByCow(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHealthRecordsByCow(arg0);
            return result;
        }
    }
    async getMilkRecordsByDate(arg0: string): Promise<Array<MilkRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMilkRecordsByDate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMilkRecordsByDate(arg0);
            return result;
        }
    }
    async getOnlineUsers(): Promise<Array<bigint>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOnlineUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOnlineUsers();
            return result;
        }
    }
    async getProfile(): Promise<GaushaalaProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfile();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfile();
            return result;
        }
    }
    async getTodayMilkRecords(): Promise<Array<MilkRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTodayMilkRecords();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTodayMilkRecords();
            return result;
        }
    }
    async getUserByPin(arg0: string): Promise<User | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserByPin(arg0);
                return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserByPin(arg0);
            return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUsersByPin(arg0: string): Promise<Array<User>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUsersByPin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUsersByPin(arg0);
            return result;
        }
    }
    async recordFeedConsumption(arg0: string, arg1: number, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordFeedConsumption(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordFeedConsumption(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async sendHeartbeat(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendHeartbeat(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendHeartbeat(arg0);
            return result;
        }
    }
    async updateCow(arg0: bigint, arg1: string, arg2: string, arg3: bigint, arg4: string, arg5: string, arg6: string, arg7: string, arg8: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCow(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCow(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
            return result;
        }
    }
    async updateFeedStock(arg0: string, arg1: number, arg2: number, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFeedStock(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFeedStock(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateProfile(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string, arg7: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProfile(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProfile(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Cow]): Cow | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_User]): User | null {
    return value.length === 0 ? null : value[0];
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
